apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: dema-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dema-deploy
  template:
    metadata:
      labels:
        app: dema-deploy
    spec:
      containers:
      - image: deyma/tiger:latest
        name: pet
